pages:
  stage: deploy
  image: node:10.6.0-alpine
  script:
    - npm install
    - npm run build
    - mv build public
  environment:
    name: production
    url: https://react-gomoku.kissgyorgy.me
  artifacts:
    paths:
    - public
